# Generated by Django 2.1.7 on 2019-04-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_grp_rel',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='check_grp_rel',
            old_name='rule_id',
            new_name='rule',
        ),
    ]
